spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: todo-service
          uri: lb:http://TODO-SERVICE
          predicates:
            - Path=/api/v1/todo/**